<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="ClassLibrary1\**" />
    <EmbeddedResource Remove="ClassLibrary1\**" />
    <None Remove="ClassLibrary1\**" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="ClassLibrary1">
      <HintPath>ClassLibrary1\bin\Debug\net10.0\ClassLibrary1.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>