<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="VisionMotionProtocolLib\**" />
    <EmbeddedResource Remove="VisionMotionProtocolLib\**" />
    <None Remove="VisionMotionProtocolLib\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="VisionMotionProtocolLib\VisionMotionProtocolLib.csproj" />
  </ItemGroup>

</Project>